--- 
server:
  error:
    whitelabel:
      enabled: false
  session:
    timeout: 1800
management:
  security:
    enabled: false
security:
  user:
    name: admin
    password: admin
  basic:
    enabled: true
    port: 8081
spring: 
  datasource: 
    password: root
    url: "jdbc:mysql://localhost:3306/test?useSSL=false"
    username: root
  jpa: 
    generate-ddl: false
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
